version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.2
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.2
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: s3
        PYTHON_DEPS: sqlalchemy==1.2.0 psycopg2-binary boto3 ipython-sql
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      - ./airflow/plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
volumes:
  pgdata:
    driver: local